name: 'build'

on: [ 'push', 'pull_request' ]

jobs:
    build:
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: 'ubuntu-latest'
        steps:
            -   name: 'checkout repo'
                uses: 'actions/checkout@v2'
            -   name: 'setup JDK 1.8'
                uses: 'actions/setup-java@v1'
                with:
                    java-version: 1.8
            -   name: 'build'
                run: './gradlew build'
            -   name: 'publish'
                if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
                run: './gradlew publish'
                env:
                    ORG_GRADLE_PROJECT_unnamedRepositoryUsername: '${{ secrets.REPO_USER }}'
                    ORG_GRADLE_PROJECT_unnamedRepositoryPassword: '${{ secrets.REPO_PASSWORD }}'